### ISSUE TITLE
git 2.38.1 breaks basics::it_loads_a_submodule test

### ISSUE THREAD

**Issue by turboMaCk** [cargo-generate/cargo-generate#777]
Most of the template doesn't apply since this bug was hit while packing cargo-generate not while using it.

**Describe the bug**
In environment with git 2.38.1 test ` basics::it_loads_a_submodule` seems to fail. See [info about git release](https://www.phoronix.com/news/Git-2.38.1-Released). I think patches to the mentioned CVEs are likely the culprit.

```
failures:

---- basics::it_loads_a_submodule stdout ----
thread 'basics::it_loads_a_submodule' panicked at 'Unexpected failure.
code-128
stderr=```"Cloning into \'/build/.tmpWg7xJ7/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///build/.tmptH4CUn\' into submodule path \'/build/.tmpWg7xJ7/submodule\' failed\n"```
command=`"git" "submodule" "add" "file:///build/.tmptH4CUn" "./submodule/"`
code=128
stdout=""
stderr="Cloning into \'/build/.tmpWg7xJ7/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///build/.tmptH4CUn\' into submodule path \'/build/.tmpWg7xJ7/submodule\' failed\n"
', /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**make sure you**
- [x] ~I'm on the latest rust version `rustup update`~ yes but using nix instead of rustup
- [x] ~I'm on the latest cargo-generate version `cargo install cargo-generate`~ installed via nix

**To Reproduce**
1. `cargo test` on system with git 2.38.1
2. above

**Expected behavior**
Tests should pass

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: `Linux nixos-mainframe 5.15.75 #1-NixOS SMP Wed Oct 26 10:35:57 UTC 2022 x86_64 GNU/Linux`
 - Build tools: gnu
 - Shell: zsh & bash
 - `rustc --version`: 1.64.0
 - `cargo generate --version`: 0.16.0

**Additional context**
downstream fix https://github.com/NixOS/nixpkgs/pull/199668

**Comment by turboMaCk** [comment]
I was able to replicate the failure using cargo (after I patched my system which depends on cargo-generate):

Using HEAD (master branch):

<details>

```
$ git remote show origin
* remote origin
  Fetch URL: git@github.com:cargo-generate/cargo-generate.git
  Push  URL: git@github.com:cargo-generate/cargo-generate.git
  HEAD branch: main
  Remote branches:
    Update-git_config                       tracked
    cargo-generate-526                      tracked
    cargo-generate-79                       tracked
    cargo_generate_guide                    tracked
    dependabot/cargo/anyhow-1.0.66          tracked
    dependabot/cargo/assert_cmd-2.0.5       tracked
    dependabot/cargo/clap-4.0.18            tracked
    dependabot/cargo/git-config-0.9.0       tracked
    dependabot/cargo/home-0.5.4             tracked
    dependabot/cargo/path-absolutize-3.0.14 tracked
    dependabot/cargo/serde-1.0.147          tracked
    favorite_git_path_refactor              tracked
    feat/405                                tracked
    feat/516                                tracked
    fix/510                                 tracked
    fix/514                                 tracked
    gh-pages                                tracked
    main                                    tracked
    project-dir                             tracked
    v0.5.x                                  tracked
  Local branch configured for 'git pull':
    main merges with remote main
  Local ref configured for 'git push':
    main pushes to main (up to date)


$ git rev-parse HEAD
a1c5b47021e2dc35306df00fd6782d5569bcd205
```

</details>

With these versions:

```
$ git --version
git version 2.38.1

$ cargo --version
cargo 1.64.0

$ rustc --version
rustc 1.64.0
```

running tests produces the failure:

```
$ cargo test

---- basics::it_loads_a_submodule stdout ----
thread 'basics::it_loads_a_submodule' panicked at 'Unexpected failure.
code-128
stderr=```"Cloning into \'/tmp/.tmp1YXfVC/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///tmp/.tmpRK0WGI\' into submodule path \'/tmp/.tmp1YXfVC/submodule\' failed\n"```
command=`"git" "submodule" "add" "file:///tmp/.tmpRK0WGI" "./submodule/"`
code=128
stdout=""
stderr="Cloning into \'/tmp/.tmp1YXfVC/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///tmp/.tmpRK0WGI\' into submodule path \'/tmp/.tmp1YXfVC/submodule\' failed\n"
', /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    basics::it_loads_a_submodule

test result: FAILED. 84 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 0.60s
```

See detauls for `RUST_BACKTRACE=1` results:

<details>


```
failures:

---- basics::it_loads_a_submodule stdout ----
thread 'basics::it_loads_a_submodule' panicked at 'Unexpected failure.
code-128
stderr=```"Cloning into \'/tmp/.tmp73SZax/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///tmp/.tmpM4q4EN\' into submodule path \'/tmp/.tmp73SZax/submodule\' failed\n"```
command=`"git" "submodule" "add" "file:///tmp/.tmpM4q4EN" "./submodule/"`
code=128
stdout=""
stderr="Cloning into \'/tmp/.tmp73SZax/submodule\'...\nfatal: transport \'file\' not allowed\nfatal: clone of \'file:///tmp/.tmpM4q4EN\' into submodule path \'/tmp/.tmp73SZax/submodule\' failed\n"
', /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
             at /build/rustc-1.64.0-src/library/core/src/panicking.rs:72:5
   3: assert_cmd::assert::AssertError::panic
             at /home/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-2.0.4/src/assert.rs:1036:9
   4: core::ops::function::FnOnce::call_once
             at /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
   5: core::result::Result<T,E>::unwrap_or_else
             at /build/rustc-1.64.0-src/library/core/src/result.rs:1493:23
   6: assert_cmd::assert::Assert::success
             at /home/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-2.0.4/src/assert.rs:156:9
   7: integration::helpers::project_builder::ProjectBuilder::build::{{closure}}
             at ./tests/integration/helpers/project_builder.rs:159:17
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /build/rustc-1.64.0-src/library/core/src/slice/iter/macros.rs:211:21
   9: integration::helpers::project_builder::ProjectBuilder::build
             at ./tests/integration/helpers/project_builder.rs:158:13
  10: integration::basics::it_loads_a_submodule
             at ./tests/integration/basics.rs:823:20
  11: integration::basics::it_loads_a_submodule::{{closure}}
             at ./tests/integration/basics.rs:816:1
  12: core::ops::function::FnOnce::call_once
             at /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    basics::it_loads_a_submodule

test result: FAILED. 84 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 0.59s
```


</details>

**Comment by turboMaCk** [comment]
seems github doesn't cascade `closes/resolved` keywords as prs get closed :thinking:

**Comment by turboMaCk** [comment]
closed by https://github.com/cargo-generate/cargo-generate/pull/780
